ANGR_DECOMPILER = "angr"
IDA_DECOMPILER = "ida"
BINJA_DECOMPILER = "binja"
GHIDRA_DECOMPILER = "ghidra"
JADX_DECOMPILER = "jadx"

SUPPORTED_DECOMPILERS = {
    ANGR_DECOMPILER, IDA_DECOMPILER, BINJA_DECOMPILER, GHIDRA_DECOMPILER,
    JADX_DECOMPILER,
}
